openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  description: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: Petstore
    description: Petstore
paths:
  /pets/createPet:
    $ref: "pets/createPet.yaml"
  /pets:
    $ref: "pets/getAllPets.yaml"
  /pets/{petId}:
    $ref: "pets/getPetById.yaml"
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    CommonRq:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: request identification
          example: my request
    CommonRs:
      type: object
      required:
        - code
      properties:
        code:
          description: response code
          type: integer
        description:
          description: response description
          type: string
          maxLength: 1000